description "Kvanta5 Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env KVANTA5D_BIN="/usr/bin/kvanta5d"
env KVANTA5D_USER="kvanta5"
env KVANTA5D_GROUP="kvanta5"
env KVANTA5D_PIDDIR="/var/run/kvanta5d"
# upstart can't handle variables constructed with other variables
env KVANTA5D_PIDFILE="/var/run/kvanta5d/kvanta5d.pid"
env KVANTA5D_CONFIGFILE="/etc/kvanta5/kvanta5.conf"
env KVANTA5D_DATADIR="/var/lib/kvanta5d"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # kvanta5d will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$KVANTA5D_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run kvanta5d."
        echo "The setting must appear in $KVANTA5D_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Kvanta5 Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$KVANTA5D_PIDDIR"
    chmod 0755 "$KVANTA5D_PIDDIR"
    chown $KVANTA5D_USER:$KVANTA5D_GROUP "$KVANTA5D_PIDDIR"
    chown $KVANTA5D_USER:$KVANTA5D_GROUP "$KVANTA5D_CONFIGFILE"
    chmod 0660 "$KVANTA5D_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$KVANTA5D_PIDFILE" \
    --chuid $KVANTA5D_USER:$KVANTA5D_GROUP \
    --exec "$KVANTA5D_BIN" \
    -- \
    -pid="$KVANTA5D_PIDFILE" \
    -conf="$KVANTA5D_CONFIGFILE" \
    -datadir="$KVANTA5D_DATADIR" \
    -disablewallet \
    -daemon

